http-server = {
  port = 8080
  port = ${?SCRAPPER_PORT}
  version = "0.1.0"
}

bot = {
  base-uri = "http://bot"
  port = 8081
  port = ${?BOT_PORT}
  timeout = 500 ms
}

github = {
    base-uri = "https://api.github.com"
    api-version = "2022-11-28"
    api-token = ${GITHUB_API_TOKEN}
    timeout = 500 ms
}

stack-overflow = {
    base-uri = "https://api.stackexchange.com"
    api-version = "2.3"
    api-key = ${STACKOVERFLOW_API_KEY}
    timeout = 500 ms
}

updater = {
  interval = 30 seconds
  cron-expression = "0 */1 * * * ?"
}

update-processing = {
  batch-size = 250
  parallel-threads = 4
}

database = {
  access-type = "sql"
  driver = org.postgresql.Driver
  url = "jdbc:postgresql://postgres:5432/link_tracker"
  user = "sychenator"
  password = "CurseYou-PerryThePlatypus"
  changelog = "changelog.xml"
}

link-update-producer = {
  topic = "link.raw-updates"
  properties = {
    "bootstrap.servers" = "kafka0:9092"
    "sasl.mechanism" = ""
    "security.protocol" = "PLAINTEXT"
    "sasl.jaas.config" = ""
    "client.id" = "scrapper"
    "linger.ms" = "1"
    "acks" = "-1"
  }
}

http-client = {
    circuit-breaker = {
        max-failures = 3
        reset-timeout = 1.seconds
    }

    retry = {
        max-retries = 3
        backoff-delay = 50 ms
    }

    rate-limiting = {
        max-concurrent = 1
    }
}

message-sender-mode = kafka

valkey = {
  uri = "redis://valkey:6379"
  ttl = 24 hours
}
