ai-consumer = {
  topic = "link.raw-updates"
  properties = {
    "bootstrap.servers" = "kafka0:9092"
    "sasl.mechanism" = ""
    "security.protocol" = "PLAINTEXT"
    "sasl.jaas.config" = ""
    "group.id" = "ai-agent"
    "auto.offset.reset" = "earliest"
  }
}
ai-producer = {
  topic = "link.processed-updates"
  properties = {
    "bootstrap.servers" = "kafka0:9092"
    "sasl.mechanism" = ""
    "security.protocol" = "PLAINTEXT"
    "sasl.jaas.config" = ""
    "client.id" = "ai-agent"
    "acks" = "-1"
  }
}

ai-processing = {
    max-length = 20
    blocked-authors = []
    stop-words = ["lalala"]
}