tg-bot = {
  base-url = "https://api.telegram.org/bot"
  token = ${?TELEGRAM_TOKEN}
  bot-name = ${?TELEGRAM_BOT_NAME}
}

http-server = {
  port = 8081
  port = ${?BOT_PORT}
  version = "0.1.0"
}

scrapper = {
  base-uri = "http://scrapper"
  port = 8080
  port = ${?SCRAPPER_PORT}
  timeout = 500 ms
}

link-update-consumer = {
  topic = "link.processed-updates"
  properties = {
    "bootstrap.servers" = "kafka0:9092"
    "sasl.mechanism" = ""
    "security.protocol" = "PLAINTEXT"
    "sasl.jaas.config" = ""
    "group.id" = "bot"
    "auto.offset.reset" = "earliest"
  }
}

http-client = {
    circuit-breaker = {
        max-failures = 3
        reset-timeout = 1.seconds
    }

    retry = {
        max-retries = 3
        backoff-delay = 50 ms
    }

    rate-limiting = {
        max-concurrent = 1
    }
}
